# Generated by Django 5.2.4 on 2025-08-02 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_conceptoftheday_contest_submission_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('concept_type', models.CharField(default='DP', max_length=50)),
                ('date', models.DateField(unique=True)),
                ('example_code', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConceptOfTheDay',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_time',
        ),
        migrations.AddField(
            model_name='contest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, to='auth_app.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='problems_solved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='problems_solved',
            field=models.ManyToManyField(blank=True, to='auth_app.problem'),
        ),
    ]
