"""
Django settings for oj_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file (if available)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed

# For AWS deployment, also try to load from system environment
# This ensures environment variables are loaded even if .env file is not present

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # Fallback secret key for production
    SECRET_KEY = 'django-insecure-gh42c=oebk5h-wf2@m_vwe+dtef9kb#ck#6nv%@w4a!9vxm*_%'

# SECURITY WARNING: don't run with debug turned on in production!
# Check if we're on AWS (production) or local development
IS_PRODUCTION = os.getenv('IS_PRODUCTION', 'False').lower() == 'true'

# For AWS deployment, check if we're running on EC2
if os.path.exists('/sys/hypervisor/uuid') or os.path.exists('/proc/1/cgroup'):
    # We're on AWS/EC2
    IS_PRODUCTION = True
    DEBUG = False
else:
    # We're on local machine
    IS_PRODUCTION = False
    DEBUG = True

ALLOWED_HOSTS = [
    "13.234.242.181",
    "fullmoon.icu",
    "www.fullmoon.icu",
    "localhost",
    "127.0.0.1",
    "*"  # Keep wildcard for development
]

# Add Railway hostname to allowed hosts
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://fullmoon.icu",
    "https://www.fullmoon.icu",
    "http://13.234.242.181",
    "http://fullmoon.icu",
    "http://www.fullmoon.icu",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Ensure Railway is trusted for CSRF origins to allow POST requests
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

# HTTPS settings for proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # New modular apps
    'accounts',
    'judge',
    'compiler',
    'ai_review',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oj_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Project-level shared templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oj_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Ensure database directory exists and database file is accessible
import os
db_path = os.path.join(BASE_DIR, 'db.sqlite3')
db_dir = os.path.dirname(db_path)

# Create database directory if it doesn't exist
if not os.path.exists(db_dir):
    os.makedirs(db_dir, exist_ok=True)

# Check if database file exists, if not create it
if not os.path.exists(db_path):
    print(f"⚠️  Database file not found at {db_path}")
    print("⚠️  Creating new database file...")
    # This will be created when migrations are run
else:
    print(f"✅ Database file found at {db_path}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Add static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files storage with WhiteNoise
if IS_PRODUCTION:
    # Use simpler storage for production to avoid issues
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google AI API Configuration
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
if not GOOGLE_API_KEY:
    print("⚠️  WARNING: GOOGLE_API_KEY environment variable not set.")
    print("⚠️  AI Review functionality will be disabled.")
else:
    print(f"✅ Google API Key loaded: {GOOGLE_API_KEY[:10]}...")

# Login/Logout URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'

# Session Configuration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Security settings for production
if IS_PRODUCTION:
    print("🚀 Running in PRODUCTION mode (AWS)")
    
    # Security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Logging configuration
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'django.log',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'judge': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'compiler': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'accounts': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'home': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'ai_review': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }
    
    # Additional production settings
    SECURE_SSL_REDIRECT = False  # Set to True if using HTTPS
    SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS
    CSRF_COOKIE_SECURE = False  # Set to True if using HTTPS
    
    # Ensure static files are collected
    print("📁 Static files will be collected to:", STATIC_ROOT)
else:
    print("💻 Running in DEVELOPMENT mode (Local)")
